# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.

name: Master workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  license-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: reuse lint
        uses: fsfe/reuse-action@v2

  fossa-check:
    runs-on: ubuntu-latest
    needs: license-check
    steps:
      - uses: actions/checkout@v4

      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 0c3bbcdf20e157bbd487dae173751b28
          
  build:
    runs-on: ubuntu-latest
    needs: fossa-check
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Unit tests
        run: go test ./...
        
  docker-build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          
      - uses: docker/setup-buildx-action@v3.0.0
      
      - name: Build Docker image
        run: make docker-build

      - uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: ${{ secrets.ACR_TOKEN_NAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Tag Docker image
        run: docker tag 5gc-amf:0.0.1-dev jayaramrcdac/amf

      - name: Push Docker image to Docker Hub
        run: docker push jayaramrcdac/amf

      - name: Cleanup Docker images
        run: docker image prune -af
